version: "3.7"
services:
  app:
    image: kooldev/node:14-nest
    command:
    - npm
    - run
    - start:dev
    ports:
    - ${KOOL_APP_PORT:-3000}:3000
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
    restart: on-failure
  database:
    image: postgres:13-alpine
    ports:
    - ${KOOL_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE-database}
      POSTGRES_USER: ${TYPEORM_USERNAME-user}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD-pass}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - database:/var/lib/postgresql/data:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -q
      - -d
      - $TYPEORM_DATABASE
      - -U
      - $TYPEORM_USERNAME
  cache:
    image: redis:6-alpine
    volumes:
    - cache:/data:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
volumes:
  database: null
  cache: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
